# Generated by Django 4.2.21 on 2025-05-09 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['id']},
        ),
    ]
